name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 21 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Due to the lack of activity, the current issue is marked as stale and will be closed after 20 days, any update will remove the stale label'
        stale-pr-message: 'Due to the lack of activity, the current pr is marked as stale and will be closed after 180 days, any update will remove the stale label'
        stale-issue-label: 'inactive'
        stale-pr-label: 'inactive'
        exempt-issue-labels: 'feature,bug,enhancement,improvement,wontfix,todo,guide,doc,help wanted'
        exempt-pr-labels: 'feature,bug,enhancement,improvement,wontfix,todo,guide,doc,help wanted'
        exempt-all-milestones: true

        days-before-issue-stale: 15
        days-before-issue-close: 20
        days-before-pr-stale: 30
        days-before-pr-close: 180
        operations-per-run: 10
        start-date: '2017-10-01T00:00:00Z'

        exempt-all-assignees: true
        remove-stale-when-updated: true
        exempt-all-pr-milestones: true
        delete-branch: false
        enable-statistics: true
